name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: login to DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - name: build docker images
        run: docker-compose build
      - name: run standardrb
        run: docker-compose run --rm runner bundle exec standardrb
      - name: run rspec
        run: docker-compose run --rm runner bundle exec rspec
