name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: docker-compose build
      - run: docker-compose run --rm runner bundle install
      - run: docker-compose run --rm runner yarn install --check-files
      - run: docker-compose run --rm -e RAILS_ENV=test runner bundle exec rails db:create
      - run: docker-compose run --rm runner standardrb
      - run: docker-compose run --rm runner bundle exec rspec
